# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in bellproject.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rubocop", "~> 1.21"

gem 'webrick', "~> 1.8.2"

gem 'github-markup', '~> 5.0.1'

gem 'github-markdown', '~> 0.6.9'

gem 'erb', "~> 4.0.4"

gem 'tty-prompt', '~> 0.23.1'

gem 'progressbar', '~> 1.13.0'
